avance: 1

potion:
    nb_potions: 0
    potionduration: 3
    strengh: true
    resitance: true
    fire_resitance: true

nb_vie: 3

looting: true

hunted:
    hunted_info: true
    hunted_distance: 50

hunter:
    hunter_info: true
    hunter_distance: 500

piglin:
    piglin_drop: true
    pearldropchance: 35
    
compass:
    givecompass: true
    customcraft: false

keepinvhunted: false
restockbug: false